-- CREATE TABLE  etudiant (
--     id int NOT NULL  PRIMARY KEY,
--     nom varchar(255) NOT NULL,
--     prenom varchar(255) NOT NULL,
--     dateDeNaissance varchar(255) NOT NULL,
--     noteMath double NULL,
--     notePhysique double NULL,
--     noteLitterature double NULL,
--     noteSVt double NULL,
--     noteChimie double NULL,
--     noteHistoire double NULL,
--     noteGeographie double NULL,
--     noteFrancais double NULL,
--     noteAnglais double NULL,
--     noteAllemand double NULL,
--     Moyenne double NULL,
--     Mention VARCHAR(255) NULL
-- );

-- INSERT INTO etudiant (
--     idEtudiant,
--     nom,
--     prenom,
--     dateDeNaissance,
--     noteMath,
--     notePhysique,
--     noteLitterature,
--     noteChimie,
--     noteSVT,
--     noteHistoire,
--     noteGeographie,
--     noteFrancais,
--     noteAnglais,
--     noteAllemand,
--     Moyenne,
--     Mention
--   )
-- VALUES (
--     121351,
--     'Jmal',
--     'Skander',
--     '09/04/2003',
--     12,
--     10,
--     14,
--     9,
--     13,
--     15,
--     11,
--     16,
--     12,
--     17,
--     12.50,
--     "Bien"
--   );
-- INSERT INTO  etudiant (
--     idEtudiant,
--     nom,
--     prenom,
--     dateDeNaissance,
--     noteMath,
--     notePhysique,
--     noteLitterature,
--     noteChimie,
--     noteSVT,
--     noteHistoire,
--     noteGeographie,
--     noteFrancais,
--     noteAnglais,
--     noteAllemand,
--     Moyenne,
--     Mention
--   )
-- VALUES (
--     128353,
--     'Zayen',
--     'Ali',
--     '01/08/2003',
--     14,
--     18.5,
--     17,
--     20,
--     15.5,
--     12.25,
--     16.75,
--     19,
--     12,
--     17.5,
--     16.33,
--     "Très Bien"
--   );
-- INSERT INTO  etudiant (
--     idEtudiant,
--     nom,
--     prenom,
--     dateDeNaissance,
--     noteMath,
--     notePhysique,
--     noteLitterature,
--     noteChimie,
--     noteSVT,
--     noteHistoire,
--     noteGeographie,
--     noteFrancais,
--     noteAnglais,
--     noteAllemand,
--     Moyenne,
--     Mention
--   )
-- VALUES (
--     138453,
--     'Adouni',
--     'Med Ali',
--     '14/02/2003',
--     13.5,
--     17,
--     20,
--     10,
--     9,
--     19.5,
--     12,
--     13,
--     14,
--     15.25,
--     13.59,
--     "Bien"
--   );
  
INSERT INTO  etudiant (
    idEtudiant,
    nom,
    prenom,
    dateDeNaissance,
    noteMath,
    notePhysique,
    noteLitterature,
    noteChimie,
    noteSVT,
    noteHistoire,
    noteGeographie,
    noteFrancais,
    noteAnglais,
    noteAllemand,
    Moyenne,
    Mention
  )
VALUES (
    142357,
    'Slama',
    'Med Amine',
    '12/03/2003',
    15.5,
    17,
    14.25,
    18.75,
    11.5,
    10,
    16,
    12.25,
    20,
    15.25,
    16,
    "Très Bien"
  );
  
